[package]
name = "dioxus-cli-config"
version = "0.6.2"
edition = "2021"
authors = ["Jonathan Kelley", "Evan Almloff"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
description = "CLI Configuration for dioxus-cli"
keywords = ["web", "desktop", "mobile", "gui", "wasm"]

[dependencies]
wasm-bindgen = { workspace = true, optional = true }

[features]
web = ["dep:wasm-bindgen"]
